[package]
name = "snypeyou" 
version = "1.1.0"
authors = ["Peter J, Severin J, Kivik j"]

[[bin]]
name = "snypeyou" 
path = "src/main.rs"

[dependencies]
piston_window = "0.64.0"
find_folder = "0.3.0"
rand = "0.3.14"

